### ISSUE TITLE
Upgraded to 0.7.1 and it broke

### ISSUE THREAD

**Issue by hermanc-fda** [UX-and-I/storybook-design-token#16]
ERROR in /xxx/node_modules/storybook-design-token/dist/components/TokenOverview.js
Module not found: Error: [CaseSensitivePathsPlugin] `/xxx/node_modules/storybook-design-token/dist/components/presenter/TokenPresenter.js` does not match the corresponding path on disk `Presenter`.
 @ /xxx/node_modules/storybook-design-token/dist/components/TokenOverview.js 15:23-60

And a few other similar errors. I'm going to downgrade back to 0.5.1 now.

**Comment by Sqrrl** [comment]
Hey, I renamed some stuff recently. Looks like a case sensitivity problem with the repo and git. What OS are you using?

**Comment by Sqrrl** [comment]
Just released v0.7.2 that should fix the issue. Would be great if you could verify. Sorry for the hassle.

**Comment by hermanc-fda** [comment]
No prob, lemme try now. Mac OS Catalina. No need to apologize - I paid you nothing for it :)

**Comment by hermanc-fda** [comment]
hmmm same problem; also get a similar error (I got this error before too):

ERROR in /xxx/node_modules/storybook-design-token/dist/components/HardCodedValuesTable.js
Module not found: Error: [CaseSensitivePathsPlugin] `/xxx/node_modules/storybook-design-token/dist/components/primitives/Card.js` does not match the corresponding path on disk `Primitives`.
 @ /xxx/node_modules/storybook-design-token/dist/components/HardCodedValuesTable.js 4:13-41

ERROR in /xxx/node_modules/storybook-design-token/dist/components/TokenOverview.js
Module not found: Error: [CaseSensitivePathsPlugin] `/xxx/node_modules/storybook-design-token/dist/components/primitives/Card.js` does not match the corresponding path on disk `Primitives`.
 @ /xxx/node_modules/storybook-design-token/dist/components/TokenOverview.js 16:13-41

ERROR in /xxx/node_modules/storybook-design-token/dist/components/HardCodedValuesTable.js
Module not found: Error: [CaseSensitivePathsPlugin] `/xxx/node_modules/storybook-design-token/dist/components/primitives/Collapsible.js` does not match the corresponding path on disk `Primitives`.
 @ /xxx/node_modules/storybook-design-token/dist/components/HardCodedValuesTable.js 5:20-55

ERROR in /xxx/node_modules/storybook-design-token/dist/components/TokenOverview.js
Module not found: Error: [CaseSensitivePathsPlugin] `/xxx/node_modules/storybook-design-token/dist/components/primitives/Collapsible.js` does not match the corresponding path on disk `Primitives`.
 @ /xxx/node_modules/storybook-design-token/dist/components/TokenOverview.js 17:20-55

and a few more

**Comment by hermanc-fda** [comment]
![image](https://user-images.githubusercontent.com/60711219/78471044-f7c83100-76e2-11ea-8e86-3187b91eea7f.png)

**Comment by Sqrrl** [comment]
This is strange. The case sensitivity issue with directories `primitives` and `presenter` should be fixed. Could you delete your node_modules and make a clean install? Inside `node_modules/storybook-design-token/dist/components`: Do you see the folders `primitives` and `presenter` or `Primitives` and `Presenter`?

**Comment by hermanc-fda** [comment]
Looks like the compile error is gone - thanks. I'm also getting this: any ideas?

![image](https://user-images.githubusercontent.com/60711219/78525214-64970600-778b-11ea-8286-4fe9cc457a2b.png)

I followed the trace and got here:

![image](https://user-images.githubusercontent.com/60711219/78525247-7678a900-778b-11ea-84b0-545cd13faa78.png)

And my .scss file exists and has the proper annotations (it was working fine before).

**Comment by hermanc-fda** [comment]
If it helps, here is my preview.js:

`import { addParameters } from "@storybook/react";

const scssReq = require.context("!!raw-loader!../shared", true, /.\.scss$/);
const scssTokenFiles = scssReq
  .keys()
  .map(filename => ({ filename, content: scssReq(filename).default }));

addParameters({
  options: {
    showRoots: true
  },
  designToken: {
    files: {
      scss: scssTokenFiles
    }
  }
});
`

and my scss file is in the shared folder and it's valid.

**Comment by Sqrrl** [comment]
Could you post the content of your __design-tokens.scss?

**Comment by hermanc-fda** [comment]
I cut it down to this and it's still throwing the error:

![image](https://user-images.githubusercontent.com/60711219/78950092-7fff5b00-7a82-11ea-83ab-d295fccaa975.png)


/**
 * @tokens Colors
 * @presenter Color
 */

$color-base-accents-blue: #0033a1;

**Comment by Sqrrl** [comment]
Sorry, still cannot reproduce. Could you provide a reproduction repo? Are you using a custom webpack config? Maybe something is interfering with the loader.

**Comment by Sqrrl** [comment]
@hermanc-fda I'm closing this for now. Please re-open if you think it's still broken.
